# Generated by Django 2.0.1 on 2018-01-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='label',
            field=models.IntegerField(null=True),
        ),
    ]
