# Generated by Django 2.0.1 on 2018-01-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_images_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
