# Generated by Django 2.0.1 on 2018-01-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180116_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mnistnn',
            name='path',
        ),
        migrations.AddField(
            model_name='mnistnn',
            name='accuracy',
            field=models.IntegerField(null=True),
        ),
    ]
