# Generated by Django 2.0.1 on 2018-01-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180116_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='image/testset/')),
            ],
        ),
    ]
